### ISSUE TITLE
please provide version which works with debian

### ISSUE THREAD

**Issue by andrewufrank** [hermlnx/system-config-lvm-1.1.18#1]
I tried to install your version for ubunto bionic but it misses packages, i do not find on debian buster (debian 10). Your wrote in python (?) and i hope it is easy to complete the package list with 
the necessary packages for work on debian 10. 
greatly appreciated - your tool would respond to serious demands!

if i can help, contact me! (but I have not much experience with package management neither python).

andrew

**Comment by hermlnx** [comment]
The package relies on depreciated python2 and gtk2 features that are no longer supportable in Debian as per the projects policies.
